service: serverless-music
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-west-2

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
        - "s3:GetObject"
        - "dynamodb:Query"
        - "sqs:SendMessage"
        - "logs:PutLogEvents"
      Resource: "*"

plugins:
  - serverless-offline
  - serverless-express

functions:
  auth:
    handler: auth.handler
    
  listArtists:
    handler: handler.api
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
          authorizer:
            name: auth
            type: request
            identitySource: method.request.header.authorization

  receivePlay:
    handler: handler.receivePlay
    events:
      - sqs: arn:aws:sqs:us-west-2:243732450758:play-music-queue

# resources:
#   Resources:
#     MyQueue:
#       Type: "AWS::SQS::Queue"
#       Properties:
#         QueueName: "play-music-queue"